### ISSUE TITLE
Bug no scroll de uma  tabela;

### ISSUE THREAD

**Issue by soares-eduardo** [soares-eduardo/supabase#7]
Link: https://github.com/supabase/supabase/issues/8122

**Comment by lnardon** [comment]
Bug não foi possível de ser recriado localmente nem no video da issue demonstrado abaixo.

https://github.com/supabase/supabase/issues/8122#issuecomment-1227632879
Safari version is: Version 15.6.1 (17613.3.9.1.16)


O relator do bug  informou que foi arrumado na ultima atualização dos macOS e do navegador safari.
